dependencies:
  - python==3.10
  - pip
  - pip:
      - matplotlib==3.7.1
      - dvc==3.31.0
      - emcee==3.1.4
      - corner==2.2.1
      - lyscripts==0.7.3
      - tueplots==0.0.6
      - Jinja2==3.1.2
      - beautifulsoup4==4.11.1
